"""Add foreign key for screenings

Revision ID: 1db208e3f712
Revises: df9362066b46
Create Date: 2025-09-10 22:45:29.542330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1db208e3f712'
down_revision: Union[str, Sequence[str], None] = 'df9362066b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screening_results', 'mood',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('screening_results', 'score',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('screening_results', 'overall',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('screening_results', 'challenges',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('screening_results', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('screening_results', 'created_at')
    op.drop_column('screening_results', 'email')
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.add_column('screening_results', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('screening_results', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.alter_column('screening_results', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('screening_results', 'challenges',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('screening_results', 'overall',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('screening_results', 'score',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('screening_results', 'mood',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
